[package]
name = "scfs-program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test-bpf = []

[dependencies]
solana-program = "1.9.4"

[dev-dependencies]
assert_matches = "1.4.0"
solana-program-test = "1.9.4"
solana-sdk = "1.9.4"
solana-logger = "1.9.4"

[lib]
crate-type = ["cdylib", "lib"]
