[package]
name = "sad"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
solana-clap-utils = "1.8.0"
solana-cli-config = "1.8.0"
solana-client = "1.8.0"
solana-logger = "1.8.0"
solana-remote-wallet = "1.8.0"
solana-sdk = "1.8.0"
