[package]
name = "gadgets-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.8.2"
solana-sdk = "1.8.2"
yaml-rust = "0.4.5"